# Generated by Django 4.2.6 on 2023-10-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(db_index=True, max_length=32)),
                ('text', models.TextField()),
                ('label', models.CharField(max_length=128)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo', models.CharField(db_index=True, max_length=64)),
                ('response', models.TextField()),
                ('prediction', models.CharField(max_length=256)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('smp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ripple_predict.socialmediapost')),
            ],
        ),
    ]
